apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  containers:
  - name: hello-world
    image: rancher/hello-world
    ports:
    - containerPort: 80
      protocol: TCP
    restartPolicy: Always
