apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: demo
  labels:
    app: alpine
spec:
  containers:
  - name: alpine
    image: byrnedo/alpine-curl
    command: ["tail"]
    args: ["-f", "/dev/null"]
