apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  labels:
    app: alpine
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["sh", "/mnt/entrypoint.sh"]
    volumeMounts:
    - name: entry-volume
      mountPath:  /mnt
    - name: data-volume
      mountPath:  /data
  volumes:
    - name: entry-volume
      configMap:
        name: demo-config-map
        items:
        - key:  entrypoint.sh
          path: entrypoint.sh
    - name: data-volume
      configMap:
        name: demo-config-map
        items:
        - key:  demo.txt
          path: demo.txt


