apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /hello-world
        backend:
          serviceName: hello-world-svc
          servicePort: http
      - path: /img
        backend:
          serviceName: hello-world-svc
          servicePort: http
